export const REQUEST_DEPARTMENT_BY_ID = 'REQUEST_DEPARTMENT_BY_ID';
export const RECEIVE_DEPARTMENT_BY_ID = 'RECEIVE_DEPARTMENT_BY_ID';
export const ERROR_DEPARTMENT_BY_ID = 'ERROR_DEPARTMENT_BY_ID';
