export const REQUEST_LECTOR_BY_ID = 'REQUEST_LECTOR_BY_ID';
export const RECEIVE_LECTOR_BY_ID = 'RECEIVE_LECTOR_BY_ID';
export const ERROR_LECTOR_BY_ID = 'ERROR_LECTOR_BY_ID';

export const REQUEST_PROMOTE_LECTOR_BY_ID = 'REQUEST_PROMOTE_LECTOR_BY_ID';
export const RECEIVE_PROMOTE_LECTOR_BY_ID = 'RECEIVE_PROMOTE_LECTOR_BY_ID';
export const ERROR_PROMOTE_LECTOR_BY_ID = 'ERROR_PROMOTE_LECTOR_BY_ID';

export const REQUEST_UPDATE_LECTOR_BY_ID = 'REQUEST_UPDATE_LECTOR_BY_ID';
export const RECEIVE_UPDATE_LECTOR_BY_ID = 'RECEIVE_UPDATE_LECTOR_BY_ID';
export const ERROR_UPDATE_LECTOR_BY_ID = 'ERROR_UPDATE_LECTOR_BY_ID';
